on:
  push:
    branches:
      - 'dev'
name: npm build, publish and deploy
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: dev
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/x-tool-frontend:latest

  deploy:
    name: Redeploy webhook call
    runs-on: ubuntu-latest
    needs: [build-and-publish]
    steps:
      - name: Deploy docker container webhook
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ vars.DEPLOY_WEBHOOK_URL  }}/deploy-x-tool-dev
